name: Armory Build Defaults
description: Default Variable Conventions For Armory Builds
author: Armory
inputs:
  artifactory_org:
    default: "armory"
  artifactory_docker_repository:
    default: "docker-local"
  docker_repository_prefix:
    default: "armory"
  red_hat_scan_registry_hostname:
    default: "scan.connect.redhat.com"
  red_hat_pid:
    default: ${{ secrets.REDHAT_PID }}
runs:
  using: 'node12'
  main: 'dist/index.js'
