name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'

      - run: |
          yarn
      - run: |
          yarn test
      - run: |
          yarn build && yarn package
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: commit build to dist/
          branch: main
          file_pattern: dist/*.js
